struct StratagemMapping {
  int id;
  const char* name;
  const char* sequence;
  const char* image;
  const char* filename;
};

StratagemMapping stratagems[] = {
  { 1, "Reinforce", "UDRLU", "reinforce.svg", "ui_img_reinforce_stratagem_icon_png.c" },
  { 2, "Resupply", "DDUR", "resupply.svg", "ui_img_resupply_stratagem_icon_png.c" },
  { 3, "SOS Beacon", "UDRU", "sos beacon.svg", "ui_img_sos_beacon_stratagem_icon_png.c" },
  { 4, "SEAF Artillery", "RUUD", "seaf artillery.svg", "ui_img_seaf_artillery_stratagem_icon_png.c" },
  { 5, "Hellbomb", "DULDURDU", "hellbomb.svg", "ui_img_hellbomb_stratagem_icon_png.c" },
  { 6, "Prospecting Drill", "DDLRDD", "prospecting drill.svg", "ui_img_prospecting_drill_stratagem_icon_png.c" },
  { 7, "Seismic Probe", "UULRDD", "seismic probe.svg", "ui_img_seismic_probe_stratagem_icon_png.c" },
  { 8, "Super Earth Flag", "DUDU", "super earth flag.svg", "ui_img_super_earth_flag_stratagem_icon_png.c" },
  { 10, "Machine Gun", "DLDUR", "machine gun.svg", "ui_img_machine_gun_stratagem_icon_png.c" },
  { 11, "Anti-Materiel Rifle", "DLRUD", "anti-materiel rifle.svg", "ui_img_anti-materiel_rifle_stratagem_icon_png.c" },
  { 12, "Stalwart", "DLDUUL", "stalwart.svg", "ui_img_stalwart_stratagem_icon_png.c" },
  { 13, "Expendable Anti-Tank", "DDLUR", "expendable anti-tank.svg", "ui_img_expendable_anti-tank_stratagem_icon_png.c" },
  { 14, "Recoilless Rifle", "DLRRL", "recoilless rifle.svg", "ui_img_recoilless_rifle_stratagem_icon_png.c" },
  { 15, "Flamethrower", "DLUDU", "flamethrower.svg", "ui_img_flamethrower_stratagem_icon_png.c" },
  { 16, "Autocannon", "DLDUUR", "autocannon.svg", "ui_img_autocannon_stratagem_icon_png.c" },
  { 17, "Railgun", "DRDULR", "railgun.svg", "ui_img_railgun_stratagem_icon_png.c" },
  { 18, "Spear", "DDUDD", "spear.svg", "ui_img_spear_stratagem_icon_png.c" },
  { 19, "Quasar Canon LAS-99", "DDULR", "quasar cannon.svg", "ui_img_quasar_cannon_stratagem_icon_png.c" },
  { 20, "Airburst Rocket Launcher", "DUULR", "airburst rocket launcher.svg", "ui_img_airburst_rocket_launcher_stratagem_icon_png.c" },
  { 21, "Orbital Gatling Barrage", "RDLUU", "orbital gatling barrage.svg", "ui_img_orbital_gatling_barrage_stratagem_icon_png.c" },
  { 22, "Orbital Airburst Strike", "RRR", "orbital airburst strike.svg", "ui_img_orbital_airburst_strike_stratagem_icon_png.c" },
  { 23, "Orbital 120MM HE Barrage", "RRDLRD", "orbital 120mm he barrage.svg", "ui_img_orbital_120mm_he_barrage_stratagem_icon_png.c" },
  { 24, "Orbital 380MM HE Barrage", "RDUULDD", "orbital 380mm he barrage.svg", "ui_img_orbital_380mm_he_barrage_stratagem_icon_png.c" },
  { 25, "Orbital Walking Barrage", "RDRDRD", "orbital walking barrage.svg", "ui_img_orbital_walking_barrage_stratagem_icon_png.c" },
  { 26, "Orbital Laser", "RDURD", "orbital laser.svg", "ui_img_orbital_laser_stratagem_icon_png.c" },
  { 27, "Orbital Railcannon Strike", "RUDDR", "orbital railcannon strike.svg", "ui_img_orbital_railcannon_strike_stratagem_icon_png.c" },
  { 28, "Eagle Strafing Run", "URR", "eagle strafing run.svg", "ui_img_eagle_strafing_run_stratagem_icon_png.c" },
  { 29, "Eagle Airstrike", "URDR", "eagle airstrike.svg", "ui_img_eagle_airstrike_stratagem_icon_png.c" },
  { 30, "Eagle Cluster Bomb", "URDDR", "eagle cluster bomb.svg", "ui_img_eagle_cluster_bomb_stratagem_icon_png.c" },
  { 31, "Eagle Napalm Airstrike", "URDU", "eagle napalm airstrike.svg", "ui_img_eagle_napalm_airstrike_stratagem_icon_png.c" },
  { 32, "Jump Pack", "DUUDU", "jump pack.svg", "ui_img_jump_pack_stratagem_icon_png.c" },
  { 33, "Eagle Smoke Strike", "URUD", "eagle smoke strike.svg", "ui_img_eagle_smoke_strike_stratagem_icon_png.c" },
  { 34, "Eagle 110MM Rocket Pods", "URUL", "eagle 110mm rocket pods.svg", "ui_img_eagle_110mm_rocket_pods_stratagem_icon_png.c" },
  { 35, "Eagle 500KG Bomb", "URDDD", "eagle 500kg bomb.svg", "ui_img_eagle_500kg_bomb_stratagem_icon_png.c" },
  { 36, "Eagle Rearm", "UULUR", "eagle rearm.svg", "ui_img_eagle_rearm_stratagem_icon_png.c" },
  { 37, "Orbital Precision Strike", "RRU", "orbital precision strike.svg", "ui_img_orbital_precision_strike_stratagem_icon_png.c" },
  { 38, "Orbital Gas Strike", "RRDR", "orbital gas strike.svg", "ui_img_orbital_gas_strike_stratagem_icon_png.c" },
  { 39, "Orbital EMS Strike", "RRLD", "orbital ems strike.svg", "ui_img_orbital_ems_strike_stratagem_icon_png.c" },
  { 40, "Orbital Smoke Strike", "RRDU", "orbital smoke strike.svg", "ui_img_orbital_smoke_strike_stratagem_icon_png.c" },
  { 41, "HMG Emplacement", "DULRRL", "hmg emplacement.svg", "ui_img_hmg_emplacement_stratagem_icon_png.c" },
  { 42, "Shield Generator Pack", "DULRLR", "shield generator pack.svg", "ui_img_shield_generator_pack_stratagem_icon_png.c" },
  { 43, "Tesla Tower", "DURULR", "tesla tower.svg", "ui_img_tesla_tower_stratagem_icon_png.c" },
  { 44, "Anti-Personnel Minefield", "DLUR", "anti-personnel minefield.svg", "ui_img_anti-personnel_minefield_stratagem_icon_png.c" },
  { 45, "Supply Pack", "DLDUUD", "supply pack.svg", "ui_img_supply_pack_stratagem_icon_png.c" },
  { 46, "Grenade Launcher", "DLULD", "grenade launcher.svg", "ui_img_grenade_launcher_stratagem_icon_png.c" },
  { 47, "Laser Cannon", "DLDUL", "laser cannon.svg", "ui_img_laser_cannon_stratagem_icon_png.c" },
  { 48, "Incendiary Mines", "DLLD", "incendiary mines.svg", "ui_img_incendiary_minefield_stratagem_icon_png.c" },
  { 49, "Guard Dog Rover", "DULURR", "guard dog rover.svg", "ui_img_guard_dog_rover_stratagem_icon_png.c" },
  { 50, "Ballistic Shield Backpack", "DLDDUL", "ballistic shield backpack.svg", "ui_img_ballistic_shield_backpack_stratagem_icon_png.c" },
  { 51, "Arc Thrower", "DRDULL", "arc thrower.svg", "ui_img_arc_thrower_stratagem_icon_png.c" },
  { 52, "Shield Generator Relay", "DDLRLR", "shield generator relay.svg", "ui_img_shield_generator_relay_stratagem_icon_png.c" },
  { 53, "Heavy Machine Gun MG-101", "DLUDD", "heavy machine gun.svg", "ui_img_heavy_machine_gun_stratagem_icon_png.c" },
  { 54, "Machine Gun Sentry", "DURRU", "machine gun sentry.svg", "ui_img_machine_gun_sentry_stratagem_icon_png.c" },
  { 55, "Gatling Sentry", "DURL", "gatling sentry.svg", "ui_img_gatling_sentry_stratagem_icon_png.c" },
  { 56, "Mortar Sentry", "DURRD", "mortar sentry.svg", "ui_img_mortar_sentry_stratagem_icon_png.c" },
  { 57, "Guard Dog", "DULURD", "guard dog.svg", "ui_img_guard_dog_stratagem_icon_png.c" },
  { 58, "Autocannon Sentry", "DURULU", "autocannon sentry.svg", "ui_img_autocannon_sentry_stratagem_icon_png.c" },
  { 59, "Rocket Sentry", "DURRL", "rocket sentry.svg", "ui_img_rocket_sentry_stratagem_icon_png.c" },
  { 60, "EMS Mortar Sentry", "DURDR", "ems mortar sentry.svg", "ui_img_ems_mortar_sentry_stratagem_icon_png.c" },
  { 61, "Patriot Exosuit", "LDRULDD", "patriot exosuit.svg", "ui_img_patriot_exosuit_stratagem_icon_png.c" },
  { 62, "Commando", "DLUDR", "commando.svg", "ui_img_commando_stratagem_icon_png.c" },
  { 63, "Dark Fluid Vessel", "ULRDUU", "dark fluid vessel.svg", "ui_img_dark_fluid_vessel_stratagem_icon_png.c" },
  { 64, "Emancipator Exosuit", "LDRULDU", "emancipator exosuit.svg", "ui_img_emancipator_exosuit_stratagem_icon_png.c" },
  { 67, "Anti-Materiel Rifle", "DLRUD", "Anti-Materiel Rifle.svg", "ui_img_anti-materiel_rifle_stratagem_icon_png.c" },
  { 68, "Anti-Personnel Minefield", "DLUR", "Anti-Personnel Minefield.svg", "ui_img_anti-personnel_minefield_stratagem_icon_png.c" },
  { 69, "Anti-Tank Emplacement", "DULRRR", "Anti-Tank Emplacement.svg", "ui_img_anti-tank_emplacement_stratagem_icon_png.c" },
  { 70, "Anti-Tank Mines", "DLUU", "Anti-Tank Mines.svg", "ui_img_anti-tank_mines_stratagem_icon_png.c" },
  { 71, "Directional Shield", "DULRUU", "Directional Shield.svg", "ui_img_directional_shield_stratagem_icon_png.c" },
  { 72, "Fast Recon Vehicle", "LDRDRDU", "Fast Recon Vehicle.svg", "ui_img_fast_recon_vehicle_stratagem_icon_png.c" },
  { 73, "Flame Sentry", "DURDUU", "Flame Sentry.svg", "ui_img_flame_sentry_stratagem_icon_png.c" },
  { 74, "Gas Mine", "DLLR", "Gas Mine.svg", "ui_img_gas_minefield_stratagem_icon_png.c" },
  { 75, "Guard Dog Breath", "DULURU", "Guard Dog Breath.svg", "ui_img_guard_dog_dog_breath_stratagem_icon_png.c" },
  { 76, "Orbital Illumination Flare", "RRLL", "Orbital Illumination Flare.svg", "ui_img_orbital_illumination_flare_stratagem_icon_png.c" },
  { 77, "Orbital Napalm Barrage", "RRDLRU", "Orbital Napalm Barrage.svg", "ui_img_orbital_napalm_barrage_stratagem_icon_png.c" },
  { 78, "StA-X3 W.A.S.P. Launcher", "DDUDR", "StA-X3 W.A.S.P. Launcher.svg", "ui_img_wasp_launcher_stratagem_icon_png.c" },
  { 79, "Sterilizer", "DLUDL", "Sterilizer.svg", "ui_img_sterilizer_stratagem_icon_png.c" }
};