// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_BACKUP1

#ifndef _SQUARELINE_PROJECT_BACKUP1_UI_H
#define _SQUARELINE_PROJECT_BACKUP1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Roller2;
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_Switch1;
extern lv_obj_t * ui_Slider2;
void ui_event_Image5(lv_event_t * e);
extern lv_obj_t * ui_Image5;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
void ui_event_Screen3(lv_event_t * e);
extern lv_obj_t * ui_Screen3;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
void ui_event_Button17(lv_event_t * e);
extern lv_obj_t * ui_Button17;
void ui_event_Button18(lv_event_t * e);
extern lv_obj_t * ui_Button18;
void ui_event_Button19(lv_event_t * e);
extern lv_obj_t * ui_Button19;
void ui_event_Button20(lv_event_t * e);
extern lv_obj_t * ui_Button20;
extern lv_obj_t * ui_Image3;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
extern lv_obj_t * ui_Screen5;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
// CUSTOM VARIABLES

// SCREEN: ui_Screen4
void ui_Screen4_screen_init(void);
void ui_event_Screen4(lv_event_t * e);
extern lv_obj_t * ui_Screen4;
void ui_event_Button21(lv_event_t * e);
extern lv_obj_t * ui_Button21;
void ui_event_Button22(lv_event_t * e);
extern lv_obj_t * ui_Button22;
void ui_event_Button23(lv_event_t * e);
extern lv_obj_t * ui_Button23;
void ui_event_Button24(lv_event_t * e);
extern lv_obj_t * ui_Button24;
void ui_event_Button25(lv_event_t * e);
extern lv_obj_t * ui_Button25;
extern lv_obj_t * ui_Panel1;
void ui_event_Button27(lv_event_t * e);
extern lv_obj_t * ui_Button27;
void ui_event_Button26(lv_event_t * e);
extern lv_obj_t * ui_Button26;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
void ui_event_Button28(lv_event_t * e);
extern lv_obj_t * ui_Button28;
void ui_event_Button29(lv_event_t * e);
extern lv_obj_t * ui_Button29;
void ui_event_Button30(lv_event_t * e);
extern lv_obj_t * ui_Button30;
void ui_event_Button31(lv_event_t * e);
extern lv_obj_t * ui_Button31;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_903157970);    // assets/super_earth_by_truffledude_dh0d9ze-fullview.png
LV_IMG_DECLARE(ui_img_textured_bg_png);    // assets/textured_bg.png
LV_IMG_DECLARE(ui_img_stratagem_textured_1_png);    // assets/stratagem_textured_1.png
LV_IMG_DECLARE(ui_img_hd2readyupbar_png);    // assets/hd2readyupbar.png
LV_IMG_DECLARE(ui_img_hd2togglereadyupbar_png);    // assets/hd2togglereadyupbar.png
LV_IMG_DECLARE(ui_img_settings_hd2_updated_png);    // assets/SETTINGS_HD2_updated.png
LV_IMG_DECLARE(ui_img_hd2slect_stratagems_png);    // assets/hd2SLECT_STRATAGEMS.png
LV_IMG_DECLARE(ui_img_312027341);    // assets/Helldivers-2-Logo-500x281 (1).png
LV_IMG_DECLARE(ui_img_commando_stratagem_icon_png);    // assets/Commando_Stratagem_Icon.png

// FONTS
LV_FONT_DECLARE(ui_font_Font1);

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
