// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_theme_manager.h"
#include "ui_themes.h"

// SCREEN: ui_Screen1
void ui_Screen1_screen_init(void);
void ui_event_Screen1(lv_event_t * e);
extern lv_obj_t * ui_Screen1;
extern lv_obj_t * ui_Image1;
// CUSTOM VARIABLES

// SCREEN: ui_Screen2
void ui_Screen2_screen_init(void);
void ui_event_Screen2(lv_event_t * e);
extern lv_obj_t * ui_Screen2;
extern lv_obj_t * ui_Image2;
void ui_event_Button2(lv_event_t * e);
extern lv_obj_t * ui_Button2;
// CUSTOM VARIABLES

// SCREEN: ui_Screen3
void ui_Screen3_screen_init(void);
extern lv_obj_t * ui_Screen3;
void ui_event_Button1(lv_event_t * e);
extern lv_obj_t * ui_Button1;
void ui_event_Button4(lv_event_t * e);
extern lv_obj_t * ui_Button4;
// CUSTOM VARIABLES

// SCREEN: ui_Screen5
void ui_Screen5_screen_init(void);
void ui_event_Screen5(lv_event_t * e);
extern lv_obj_t * ui_Screen5;
void ui_event_Button3(lv_event_t * e);
extern lv_obj_t * ui_Button3;
void ui_event_Button5(lv_event_t * e);
extern lv_obj_t * ui_Button5;
void ui_event_Button6(lv_event_t * e);
extern lv_obj_t * ui_Button6;
void ui_event_Button7(lv_event_t * e);
extern lv_obj_t * ui_Button7;
void ui_event_Button8(lv_event_t * e);
extern lv_obj_t * ui_Button8;
void ui_event_Button9(lv_event_t * e);
extern lv_obj_t * ui_Button9;
void ui_event_Button10(lv_event_t * e);
extern lv_obj_t * ui_Button10;
void ui_event_Button11(lv_event_t * e);
extern lv_obj_t * ui_Button11;
void ui_event_Button12(lv_event_t * e);
extern lv_obj_t * ui_Button12;
void ui_event_Button13(lv_event_t * e);
extern lv_obj_t * ui_Button13;
void ui_event_Button14(lv_event_t * e);
extern lv_obj_t * ui_Button14;
void ui_event_Button15(lv_event_t * e);
extern lv_obj_t * ui_Button15;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_903157970);    // assets/super_earth_by_truffledude_dh0d9ze-fullview.png
LV_IMG_DECLARE(ui_img_312027341);    // assets/Helldivers-2-Logo-500x281 (1).png
LV_IMG_DECLARE(ui_img_rightarrow_png);    // assets/RightArrow.png
LV_IMG_DECLARE(ui_img_leftarrow_png);    // assets/LeftArrow.png
LV_IMG_DECLARE(ui_img_eagle_airstrike_stratagem_icon_png);    // assets/Eagle_Airstrike_Stratagem_Icon.png
LV_IMG_DECLARE(ui_img_commando_stratagem_icon_png);    // assets/Commando_Stratagem_Icon.png
LV_IMG_DECLARE(ui_img_orbital_laser_stratagem_icon_png);    // assets/Orbital_Laser_Stratagem_Icon.png
LV_IMG_DECLARE(ui_img_shield_generator_pack_stratagem_icon_png);    // assets/Shield_Generator_Pack_Stratagem_Icon.png
LV_IMG_DECLARE(ui_img_862212208);    // assets/AM-23_EMS_Mortar_Sentry_Stratagem_Icon.png
LV_IMG_DECLARE(ui_img_233946757);    // assets/StA-X3_W.A.S.P._Launcher_Stratagem_Icon.png
LV_IMG_DECLARE(ui_img_273215554);    // assets/EXO-49_Emancipator_Exosuit_Stratagem_Icon.png
LV_IMG_DECLARE(ui_img_jump_pack_stratagem_icon_png);    // assets/Jump_Pack_Stratagem_Icon.png
LV_IMG_DECLARE(ui_img_resupply_stratagem_icon_png);    // assets/Resupply_Stratagem_Icon.png
LV_IMG_DECLARE(ui_img_reinforce_stratagem_icon_png);    // assets/Reinforce_Stratagem_Icon.png
LV_IMG_DECLARE(ui_img_arc_thrower_stratagem_icon_png);    // assets/Arc_Thrower_Stratagem_Icon.png
LV_IMG_DECLARE(ui_img_1248868215);    // assets/Anti-Materiel_Rifle_Stratagem_Icon.png

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
