// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_BACKUP1

#include "ui.h"
#include "Stratagem_Selection.h"
#include "stratagems_table.h"

void S3_00_BTN(lv_event_t * e)
{
	// Your code here
}

void S3_10_BTN(lv_event_t * e)
{
	// Your code here
}

void S3_11_BTN(lv_event_t * e)
{
	// Your code here
}

void S3_12_BTN(lv_event_t * e)
{
	// Your code here
}

void S3_13_BTN(lv_event_t * e)
{
	// Your code here
}

void S5_00_BTN(lv_event_t * e)
{
	// Your code here
}

void S5_01_BTN(lv_event_t * e)
{
	// Your code here
}

void S5_02_BTN(lv_event_t * e)
{
	// Your code here
}

void S5_03_BTN(lv_event_t * e)
{
	// Your code here
}

void S5_10_BTN(lv_event_t * e)
{
	// Your code here
}

void S5_11_BTN(lv_event_t * e)
{
	// Your code here
}

void S5_12_BTN(lv_event_t * e)
{
	// Your code here
}

void S5_13_BTN(lv_event_t * e)
{
	// Your code here
}

void S5_20_BTN(lv_event_t * e)
{
	// Your code here
}

void S5_21_BTN(lv_event_t * e)
{
	// Your code here
}

void S5_22_BTN(lv_event_t * e)
{
	// Your code here
}

void S5_23_BTN(lv_event_t * e)
{
	// Your code here
}

void S4_SwipeLeft(lv_event_t * e)
{
    EventsSwipeLeft();  // Trigger logic
}

void S4_SwipeRight(lv_event_t * e)
{
    EventsSwipeRight();
}

void S4_00_BTN(lv_event_t * e)
{
	// Your code here
}

void S4_01_BTN(lv_event_t * e)
{
	// Your code here
}

void S4_02_BTN(lv_event_t * e)
{
	// Your code here
}

void S4_03_BTN(lv_event_t * e)
{
	// Your code here
}

void S4_10_BTN(lv_event_t * e) 
{
	StoreToLoadout(e);
}

void S4_11_BTN(lv_event_t * e)
{
	StoreToLoadout(e);
}

void S4_12_BTN(lv_event_t * e)
{
	StoreToLoadout(e);
}

void S4_13_BTN(lv_event_t * e)
{
	StoreToLoadout(e);
}
void S4_21_BTN(lv_event_t * e)
{
	StoreToLoadout(e);
}

void S4_20_BTN(lv_event_t * e)
{
	StoreToLoadout(e);
}

void S4_22_BTN(lv_event_t * e)
{
	StoreToLoadout(e);
}

void S4_23_BTN(lv_event_t * e)
{
	StoreToLoadout(e);
}


