// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

extern bool bGUISend_Data;
extern uint16_t Status;

#define  S5_RC00_BTN            0x0001
#define  S5_RC01_BTN            0x0002
#define  S5_RC02_BTN            0x0004
#define  S5_RC03_BTN            0x0008

#define  S5_RC10_BTN            0x0010
#define  S5_RC11_BTN            0x0020
#define  S5_RC12_BTN            0x0040
#define  S5_RC13_BTN            0x0080

#define  S5_RC20_BTN            0x0100
#define  S5_RC21_BTN            0x0200
#define  S5_RC22_BTN            0x0400
#define  S5_RC23_BTN            0x0800

// #define  S5_RC30_BTN            0x1000
// #define  S5_RC31_BTN            0x2000
// #define  S5_RC32_BTN            0x4000
// #define  S5_RC33_BTN            0x8000

#ifdef __cplusplus
extern "C" {
#endif

void send_message(lv_event_t * e);
void S5_00_BTN(lv_event_t * e);
void S5_01_BTN(lv_event_t * e);
void S5_02_BTN(lv_event_t * e);
void S5_03_BTN(lv_event_t * e);
void S5_13_BTN(lv_event_t * e);
void S5_12_BTN(lv_event_t * e);
void S5_11_BTN(lv_event_t * e);
void S5_10_BTN(lv_event_t * e);
void S5_20_BTN(lv_event_t * e);
void S5_21_BTN(lv_event_t * e);
void S5_22_BTN(lv_event_t * e);
void S5_23_BTN(lv_event_t * e);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
