// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_events.h"

bool bGUISend_Data = false;
uint16_t Status = 0;


void send_message(lv_event_t * e)
{
	// Your code here
}

void S5_00_BTN(lv_event_t * e)
{
  Status |= S5_RC00_BTN;
  bGUISend_Data = true;
}

void S5_01_BTN(lv_event_t * e)
{
  Status |= S5_RC01_BTN;
  bGUISend_Data = true;
}

void S5_02_BTN(lv_event_t * e)
{
  Status |= S5_RC02_BTN;
  bGUISend_Data = true;
}

void S5_03_BTN(lv_event_t * e)
{
  Status |= S5_RC03_BTN;
  bGUISend_Data = true;
}

void S5_13_BTN(lv_event_t * e)
{
  Status |= S5_RC13_BTN;
  bGUISend_Data = true;
}

void S5_12_BTN(lv_event_t * e)
{
  Status |= S5_RC12_BTN;
  bGUISend_Data = true;
}

void S5_11_BTN(lv_event_t * e)
{
  Status |= S5_RC11_BTN;
  bGUISend_Data = true;
}

void S5_10_BTN(lv_event_t * e)
{
  Status |= S5_RC10_BTN;
  bGUISend_Data = true;
}

void S5_20_BTN(lv_event_t * e)
{
  Status |= S5_RC20_BTN;
  bGUISend_Data = true;
}

void S5_21_BTN(lv_event_t * e)
{
  Status |= S5_RC21_BTN;
  bGUISend_Data = true;
}

void S5_22_BTN(lv_event_t * e)
{
  Status |= S5_RC22_BTN;
  bGUISend_Data = true;
}

void S5_23_BTN(lv_event_t * e)
{
  Status |= S5_RC23_BTN;
  bGUISend_Data = true;
}
