// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_BACKUP1

#include "ui.h"
#include "Stratagem_Selection.h"


lv_obj_t* stratagem_buttons[8];  // bottom 8 buttons that we cycle between 


void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Screen4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Screen4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_img_src(ui_Screen4, &ui_img_textured_bg_png, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button21 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button21, 70);
    lv_obj_set_height(ui_Button21, 70);
    lv_obj_set_x(ui_Button21, -114);
    lv_obj_set_y(ui_Button21, -82);
    lv_obj_set_align(ui_Button21, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button21, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button21, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button21, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Black);
    ui_object_set_themeable_style_property(ui_Button21, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Black);
    lv_obj_set_style_bg_img_src(ui_Button21, &ui_img_stratagem_textured_1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button21, lv_color_hex(0xFFE700), LV_PART_MAIN | LV_STATE_DEFAULT);    
    lv_obj_set_style_border_opa(ui_Button21, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button21, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button22 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button22, 70);
    lv_obj_set_height(ui_Button22, 70);
    lv_obj_set_x(ui_Button22, -39);
    lv_obj_set_y(ui_Button22, -82);
    lv_obj_set_align(ui_Button22, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button22, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button22, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button22, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Black);
    ui_object_set_themeable_style_property(ui_Button22, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Black);
    lv_obj_set_style_bg_img_src(ui_Button22, &ui_img_stratagem_textured_1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button22, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button22, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button22, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button23 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button23, 70);
    lv_obj_set_height(ui_Button23, 70);
    lv_obj_set_x(ui_Button23, 37);
    lv_obj_set_y(ui_Button23, -82);
    lv_obj_set_align(ui_Button23, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button23, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button23, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button23, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Black);
    ui_object_set_themeable_style_property(ui_Button23, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Black);
    lv_obj_set_style_bg_img_src(ui_Button23, &ui_img_stratagem_textured_1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button23, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button23, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button23, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button24 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button24, 70);
    lv_obj_set_height(ui_Button24, 70);
    lv_obj_set_x(ui_Button24, 113);
    lv_obj_set_y(ui_Button24, -82);
    lv_obj_set_align(ui_Button24, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button24, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button24, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button24, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Black);
    ui_object_set_themeable_style_property(ui_Button24, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Black);
    lv_obj_set_style_bg_img_src(ui_Button24, &ui_img_stratagem_textured_1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Button24, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button24, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button24, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button25 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button25, 70);
    lv_obj_set_height(ui_Button25, 70);
    lv_obj_set_x(ui_Button25, -114);
    lv_obj_set_y(ui_Button25, 6);
    lv_obj_set_align(ui_Button25, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button25, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button25, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button25, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Black);
    ui_object_set_themeable_style_property(ui_Button25, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Black);
    // lv_obj_set_style_bg_img_src(ui_Button25, &ui_img_commando_stratagem_icon_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_user_data(ui_Button25, (void*)(intptr_t)actual_strat_index);
    lv_obj_set_style_border_color(ui_Button25, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button25, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_Screen4);
    lv_obj_set_width(ui_Panel1, 320);
    lv_obj_set_height(ui_Panel1, 10);
    lv_obj_set_x(ui_Panel1, 0);
    lv_obj_set_y(ui_Panel1, -38);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Panel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Black);
    ui_object_set_themeable_style_property(ui_Panel1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Black);
    lv_obj_set_style_bg_img_src(ui_Panel1, &ui_img_hd2togglereadyupbar_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button27 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button27, 70);
    lv_obj_set_height(ui_Button27, 70);
    lv_obj_set_x(ui_Button27, -39);
    lv_obj_set_y(ui_Button27, 82);
    lv_obj_set_align(ui_Button27, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button27, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button27, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button27, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Black);
    ui_object_set_themeable_style_property(ui_Button27, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Black);
    // lv_obj_set_style_bg_img_src(ui_Button27, &ui_img_stratagem_textured_1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_user_data(ui_Button27, (void*)(intptr_t)actual_strat_index);
    lv_obj_set_style_border_color(ui_Button27, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button27, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button26 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button26, 70);
    lv_obj_set_height(ui_Button26, 70);
    lv_obj_set_x(ui_Button26, -114);
    lv_obj_set_y(ui_Button26, 82);
    lv_obj_set_align(ui_Button26, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button26, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button26, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button26, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Black);
    ui_object_set_themeable_style_property(ui_Button26, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Black);
    // lv_obj_set_style_bg_img_src(ui_Button26, &ui_img_stratagem_textured_1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_user_data(ui_Button26, (void*)(intptr_t)actual_strat_index);
    lv_obj_set_style_border_color(ui_Button26, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button26, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button26, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button1 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button1, 70);
    lv_obj_set_height(ui_Button1, 70);
    lv_obj_set_x(ui_Button1, 37);
    lv_obj_set_y(ui_Button1, 82);
    lv_obj_set_align(ui_Button1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Black);
    ui_object_set_themeable_style_property(ui_Button1, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Black);
    // lv_obj_set_style_bg_img_src(ui_Button1, &ui_img_stratagem_textured_1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_user_data(ui_Button1, (void*)(intptr_t)actual_strat_index);
    lv_obj_set_style_border_color(ui_Button1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button1, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button28 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button28, 70);
    lv_obj_set_height(ui_Button28, 70);
    lv_obj_set_x(ui_Button28, 113);
    lv_obj_set_y(ui_Button28, 82);
    lv_obj_set_align(ui_Button28, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button28, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button28, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button28, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Black);
    ui_object_set_themeable_style_property(ui_Button28, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Black);
    // lv_obj_set_style_bg_img_src(ui_Button28, &ui_img_stratagem_textured_1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_user_data(ui_Button28, (void*)(intptr_t)actual_strat_index);
    lv_obj_set_style_border_color(ui_Button28, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button28, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button28, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button29 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button29, 70);
    lv_obj_set_height(ui_Button29, 70);
    lv_obj_set_x(ui_Button29, -39);
    lv_obj_set_y(ui_Button29, 6);
    lv_obj_set_align(ui_Button29, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button29, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button29, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button29, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Black);
    ui_object_set_themeable_style_property(ui_Button29, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Black);
    // lv_obj_set_style_bg_img_src(ui_Button29, &ui_img_stratagem_textured_1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_user_data(ui_Button29, (void*)(intptr_t)actual_strat_index);
    lv_obj_set_style_border_color(ui_Button29, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button29, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button29, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button30 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button30, 70);
    lv_obj_set_height(ui_Button30, 70);
    lv_obj_set_x(ui_Button30, 37);
    lv_obj_set_y(ui_Button30, 6);
    lv_obj_set_align(ui_Button30, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button30, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button30, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button30, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Black);
    ui_object_set_themeable_style_property(ui_Button30, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Black);
    // lv_obj_set_style_bg_img_src(ui_Button30, &ui_img_stratagem_textured_1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_user_data(ui_Button30, (void*)(intptr_t)actual_strat_index);
    lv_obj_set_style_border_color(ui_Button30, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button30, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button30, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Button31 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button31, 70);
    lv_obj_set_height(ui_Button31, 70);
    lv_obj_set_x(ui_Button31, 113);
    lv_obj_set_y(ui_Button31, 6);
    lv_obj_set_align(ui_Button31, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button31, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button31, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    ui_object_set_themeable_style_property(ui_Button31, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_COLOR,
                                           _ui_theme_color_Black);
    ui_object_set_themeable_style_property(ui_Button31, LV_PART_MAIN | LV_STATE_DEFAULT, LV_STYLE_BG_OPA,
                                           _ui_theme_alpha_Black);
    // lv_obj_set_style_bg_img_src(ui_Button31, &ui_img_stratagem_textured_1_png, LV_PART_MAIN | LV_STATE_DEFAULT);
    // lv_obj_set_user_data(ui_Button31, (void*)(intptr_t)actual_strat_index);
    lv_obj_set_style_border_color(ui_Button31, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Button31, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Button31, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Button21, ui_event_Button21, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button22, ui_event_Button22, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button23, ui_event_Button23, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button24, ui_event_Button24, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button25, ui_event_Button25, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button27, ui_event_Button27, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button26, ui_event_Button26, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button1, ui_event_Button1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button28, ui_event_Button28, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button29, ui_event_Button29, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button30, ui_event_Button30, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button31, ui_event_Button31, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Screen4, ui_event_Screen4, LV_EVENT_ALL, NULL);


    stratagem_buttons[0] = ui_Button25;
    stratagem_buttons[1] = ui_Button29;
    stratagem_buttons[2] = ui_Button30;
    stratagem_buttons[3] = ui_Button31;
    stratagem_buttons[4] = ui_Button26;
    stratagem_buttons[5] = ui_Button27;
    stratagem_buttons[6] = ui_Button1;
    stratagem_buttons[7] = ui_Button28;


    for (int i = 0; i < 8; i++) {
        int strat_index = myLoadOut.screen_strat_index + i;

        // Set the user data to the actual strat index
        lv_obj_set_user_data(stratagem_buttons[i], (void*)(intptr_t)strat_index);

        // Set the background image for the button
        const void* img_src;
        if (strat_index < stratagems_count) {
            img_src = stratagems[strat_index].icon_symbol;
        } else {
            img_src = stratagems[0].icon_symbol;  // or another default image
        }

        lv_obj_set_style_bg_img_src(stratagem_buttons[i], img_src, LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}
