// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.1
// LVGL version: 8.3.11
// Project name: SquareLine_Project_BACKUP1

#include "ui.h"


const ui_theme_variable_t _ui_theme_color_Black[3] = {0x000000, 0x000000, 0x2D2B2B};
const ui_theme_variable_t _ui_theme_alpha_Black[3] = {255, 255, 255};
uint8_t ui_theme_idx = UI_THEME_STRATBOXBG;


void ui_theme_set(uint8_t theme_idx)
{
    ui_theme_idx = theme_idx;
    _ui_theme_set_variable_styles(UI_VARIABLE_STYLES_MODE_FOLLOW);
}

